lsコマンドを作る（オブジェクト指向版）
yana-gi/ruby-practices pull request #2
Opened 2021-03-12 09:46 UTC by yana-gi

## 課題URL
[lsコマンドを作るオブジェクト指向版 \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/213)

## 参考にしたリンク
非オブジェクト指向版lsコマンドの自分の提出物
https://bootcamp.fjord.jp/products/4980
非オブジェクト指向版lsコマンドの伊藤さんの解答例
https://bootcamp.fjord.jp/products/3763

## 実行結果
`ls`から始まる結果が実際のlsコマンド、
`ruby`から始まる結果が今回作成したlsコマンドになります。

```bash
ruby-practices/08.ls_object/lib 

❯ ls ../test/sample_dir/lsDir 
Dir_a           file_a.txt      file_c.txt
Dir_b           file_b.txt      file_d.txt

❯ ruby bin_ls.rb ../test/sample_dir/lsDir 
Dir_a       file_a.txt  file_c.txt
Dir_b       file_b.txt  file_d.txt

❯ ls -a ../test/sample_dir/lsDir
.               .file_A.txt     Dir_a           file_c.txt
..              .file_B.txt     Dir_b           file_d.txt
.Dir_A          .file_C.txt     file_a.txt
.Dir_B          .file_D.txt     file_b.txt

❯ ruby bin_ls.rb -a ../test/sample_dir/lsDir
.            .file_B.txt  file_a.txt
..           .file_C.txt  file_b.txt
.Dir_A       .file_D.txt  file_c.txt
.Dir_B       Dir_a        file_d.txt
.file_A.txt  Dir_b

❯ ls -r ../test/sample_dir/lsDir
file_d.txt      file_b.txt      Dir_b
file_c.txt      file_a.txt      Dir_a

❯ ruby bin_ls.rb -r ../test/sample_dir/lsDir
file_d.txt  file_b.txt  Dir_b
file_c.txt  file_a.txt  Dir_a

❯ ls -l ../test/sample_dir/lsDir
total 32
drwxr-xr-x  2 yana  staff  64 Mar  3 17:26 Dir_a
drwxr-xr-x  2 yana  staff  64 Mar  3 17:26 Dir_b
-rw-r--r--  1 yana  staff   5 Mar  9 17:52 file_a.txt
-rw-r--r--  1 yana  staff  14 Mar  9 17:52 file_b.txt
-rw-r--r--  1 yana  staff  27 Mar  9 17:52 file_c.txt
-rw-r--r--  1 yana  staff  44 Mar  9 17:52 file_d.txt

❯ ruby bin_ls.rb -l ../test/sample_dir/lsDir
total 32
drwxr-xr-x  2 yana  staff  64  3  3 17:26 Dir_a
drwxr-xr-x  2 yana  staff  64  3  3 17:26 Dir_b
-rw-r--r--  1 yana  staff  5  3  9 17:52 file_a.txt
-rw-r--r--  1 yana  staff  14  3  9 17:52 file_b.txt
-rw-r--r--  1 yana  staff  27  3  9 17:52 file_c.txt
-rw-r--r--  1 yana  staff  44  3  9 17:52 file_d.txt

❯ ls -arl ../test/sample_dir/lsDir
total 64
-rw-r--r--   1 yana  staff   44 Mar  9 17:52 file_d.txt
-rw-r--r--   1 yana  staff   27 Mar  9 17:52 file_c.txt
-rw-r--r--   1 yana  staff   14 Mar  9 17:52 file_b.txt
-rw-r--r--   1 yana  staff    5 Mar  9 17:52 file_a.txt
drwxr-xr-x   2 yana  staff   64 Mar  3 17:26 Dir_b
drwxr-xr-x   2 yana  staff   64 Mar  3 17:26 Dir_a
-rw-r--r--   1 yana  staff   44 Mar  9 17:52 .file_D.txt
-rw-r--r--   1 yana  staff   27 Mar  9 17:52 .file_C.txt
-rw-r--r--   1 yana  staff   14 Mar  9 17:52 .file_B.txt
-rw-r--r--   1 yana  staff    5 Mar  9 17:52 .file_A.txt
drwxr-xr-x   2 yana  staff   64 Mar  3 17:26 .Dir_B
drwxr-xr-x   2 yana  staff   64 Mar  3 17:26 .Dir_A

❯ ruby bin_ls.rb -arl ../test/sample_dir/lsDir
total 64
-rw-r--r--  1 yana  staff  44  3  9 17:52 file_d.txt
-rw-r--r--  1 yana  staff  27  3  9 17:52 file_c.txt
-rw-r--r--  1 yana  staff  14  3  9 17:52 file_b.txt
-rw-r--r--  1 yana  staff  5  3  9 17:52 file_a.txt
drwxr-xr-x  2 yana  staff  64  3  3 17:26 Dir_b
drwxr-xr-x  2 yana  staff  64  3  3 17:26 Dir_a
-rw-r--r--  1 yana  staff  44  3  9 17:52 .file_D.txt
-rw-r--r--  1 yana  staff  27  3  9 17:52 .file_C.txt
-rw-r--r--  1 yana  staff  14  3  9 17:52 .file_B.txt
-rw-r--r--  1 yana  staff  5  3  9 17:52 .file_A.txt
```

## rubocop
![image](https://user-images.githubusercontent.com/67262644/110919439-9c290d80-835f-11eb-8af7-8a89a4dd65cb.png)
一つだけrubocopの警告を解決することができませんでした。
テスト結果予想のテキストをベタ書きしているため、テスト行が多くなってしまいました。

## 実装範囲
必須要件に加え、歓迎要件の以下を実装しました
* 引数に、ファイルやディレクトリを指定可能にする（歓迎要件）

## 不安なところ
全体的に不安ですが、特に下記が不安なため見て頂けると嬉しいです。

### クラス設計
クラス設計が難しかったです。
一度コードを書き始める前に考えたものの、実装してみてからもクラスを統合したり切り離したりをくり返してしまいました……。
改善案などアドバイスいただけると嬉しいです！

### テストに過不足がないか
クラスごとにテストを行っていますが、過不足がないかの判断に悩みました。
多く書くことにこしたことはないとは思いつつ、書きすぎて時間がかかってしまった印象です。
「ここのテストが足りない・不要」「ここはもっといい書き方がある」等あればご指摘お願いします……！

2021-03-18 06:48 UTC, u1tnk requested changes

2021-03-18 06:48 UTC, u1tnk commented on 08.ls_object/lib/bin_ls.rb
> +puts FormatFileList.new(parameter).get
オブジェクトの関係をもうちょっと整理した方が良いですね。

FormatFileListオブジェクトを作ってFormatFileList#getした結果をputsする。 
だと 🤔 🤔 🤔  になっちゃいます。Formatしたファイルリストをgetした結果ってFormatFileListオブジェクトっぽいけど、putsできるの？とか色々考えてしましますね。


例えば
FileListをnewしてFormatterに与えてto_sした結果をputsする。
だと(日本語としては微妙ですが)比較的分かる気がしませんか？

現状だとFormatFileListが全てをコントロールしちゃっているので機能ごとに名前をつけられた仕事以外はしないようにすると適切に分割されると思います。

2021-03-18 06:48 UTC, u1tnk commented on 08.ls_object/lib/file_list.rb
> +  def get
これは知らない方が普通とは思いますが、プログラムでのgetという単語の使われかたは「変数を読み出す程度の軽い取得処理」というイメージがあります。

いろんなソースコード見て使われ方とどういう処理かを見ていけば良いですが、とりあえずは以下のようなまとめを見て語彙を増やしましょう。ディスクからファイルを探すというニュアンスだと私なら findとかcollectとか使うかなと思います。
[関数名によく使われる英単語（動詞）の意味とニュアンス | PHP Archive](https://php-archive.net/php/words-in-function-names/)

2021-03-18 06:48 UTC, u1tnk commented on 08.ls_object/lib/format_file_list.rb
> +class FormatFileList
FileListFormatterの方がFormatがメインとなるクラスというイメージになるかと思います。
個人的にはフォーマット済みのファイルリストというニュアンスが強ければ FormattedFIleLIst と付けます。

2021-03-18 06:48 UTC, u1tnk commented on 08.ls_object/lib/parameter.rb
> +class Parameter
入力処理をまとめるのは良いですね 👍 
どうせなら引数もここにまとめちゃえば入力データが全部まとまって便利かもしれません。

2021-03-18 06:48 UTC, u1tnk commented on 08.ls_object/test/file_list_test.rb
> +# frozen_string_literal: true
テストしっかり書いてて安心感がありますね 👍

2021-03-18 06:48 UTC, u1tnk commented on 08.ls_object/lib/short_format_file.rb
> +  def initialize(file_path, file_name)
これを見ると file_pathは不要なデータなのでは無いでしょうか？

2021-03-18 06:54 UTC, u1tnk commented on 08.ls_object/test/file_list_test.rb
> +  def test_get_no_option
expectedが長くてイメージしづらいのですが、不要なデータがあるからだと思います。fileは aから dまで必要でしょうか？
specの要求を満たす最低限のファイル数にすると良いですね。

【高度なので指摘はするが対応不要】
また、現状だと今のテストデータの構造が壊れると全テスト修正する必要があります。
それぞれのtestの前の beforeでデータをrubyで作るようにして終わったら削除するとかにすると独立性が高まりますね。

2021-03-19 02:14 UTC, yana-gi commented on 08.ls_object/lib/file_list.rb
> +  def get
>これは知らない方が普通とは思いますが、プログラムでのgetという単語の使われかたは「変数を読み出す程度の軽い取得処理」というイメージがあります。

そうなると今回の`get`のような使い方は適切ではないですね……！

教えていただいた記事とても参考になります！ありがとうございます😄

2021-03-19 02:14 UTC, yana-gi commented on 08.ls_object/lib/bin_ls.rb
> +puts FormatFileList.new(parameter).get
>Formatしたファイルリストをgetした結果ってFormatFileListオブジェクトっぽいけど、putsできるの？とか色々考えてしましますね。

自分が「`FormatFileList`オブジェクトは文字列のオブジェクト」のように勘違いしてしまっていたことに気づきました。
確かに`FormatFileList`オブジェクト自体をputsしたら`#<FormatFileList:hogehoge>`のような結果が帰ってくると思ってしまいますね……！

Formatterが`to_s`した結果をputsするように修正してみようと思います。

2021-03-19 02:21 UTC, yana-gi commented on 08.ls_object/lib/format_file_list.rb
> +class FormatFileList
最後の単語のニュアンスが強くなるんですね！

このクラスの場合、Formatの機能がメインなので`FileListFormatter`の方が良さそうですね。

2021-03-19 02:21 UTC, yana-gi commented on 08.ls_object/lib/parameter.rb
> +class Parameter
>どうせなら引数もここにまとめちゃえば入力データが全部まとまって便利かもしれません。

「引数もまとめる」というのはARGVごとParameterクラスに渡すという認識であっていますか？

2021-03-19 02:22 UTC, yana-gi commented on 08.ls_object/test/file_list_test.rb
> +  def test_get_no_option
>fileは aから dまで必要でしょうか？

-lオプションなしの状態で横に３列に並んでいるかを確認したかったため（`test_no_option`など）、ディレクトリとファイル合わせて２列になるように６個作成しました。
ですが`test_option_long_and_dot_match`のようなケースの場合確かにexpectedが長くなってしまうので、隠しファイルの削除は検討してみようと思います！

>【高度なので指摘はするが対応不要】
また、現状だと今のテストデータの構造が壊れると全テスト修正する必要があります。
それぞれのtestの前の beforeでデータをrubyで作るようにして終わったら削除するとかにすると独立性が高まりますね。

まさにテストデータの追加削除や変更をするたびにテストを修正していて不便に思っていたところでした！
いい機会なのでデータをrubyで作れるようにしたいのですが、どう作るのかあまり検討がついていません🤔
自分で調べてみたのですが、疑問点を何点か確認させてください。

1. minitestでは`before`ではなく`setup`メソッドを使う、また実行後のメソッドは`teardown`を使う、という認識であっていますか？
[class MiniTest::Unit::TestCase](https://docs.ruby-lang.org/ja/2.1.0/class/MiniTest=3a=3aUnit=3a=3aTestCase.html#I_TEARDOWN)
1. テストファイルを作る際はsetup(before)内で`File.open("testfile", "w") { |f| f.print "test" }`のようにファイルを作っていく、というやり方で問題ないでしょうか？
問題ない場合、実行結果は都度変わっていきますがexpectedはどのように書けばいいでしょうか？

もちろん時間がかかるor難しいので今はやる必要がないよ、ということでしたら仰っていただければと思います😭🙏

2021-03-19 04:34 UTC, yana-gi commented
レビューありがとうございます！
何点か確認点があるため、まだ修正はしていない状態です。
ご回答お願いします🙏

また、クラス構成ですが、フィヨルドの提出物のコメント
>大きく分けて以下のような機能があると思います。
入力処理
ファイル情報収集
ファイル情報の文字列化
結果全体のフォーマット
出力処理
で、どの機能がどこらへんをクラス名、メソッド名を見て見当がつく状態を目指してみましょう 💪

を元にクラス設計と命名を考え直してみました。
|クラス| 機能 |
| --- | --- |
| Parameter|入力処理|
| FileList|ファイル情報収集|
| ShortFileFormatter|短いファイル情報を文字列化する|
| LongFileFormatter|長いファイル情報を文字列化する|
| FormattedFiles|FileListの数だけFileFormatterを呼び出す|
| FileListFormatter|FormattedFilesから結果全体をフォーマットする|

これから修正するところなのですが、なにかアドバイスがあればお教えください🙏

2021-03-21 01:22 UTC, u1tnk commented on 08.ls_object/lib/format_file_list.rb
> +class FormatFileList
> 最後の単語のニュアンスが強くなるんですね！

そう言われてなんでかな？と考えてみましたが、単純に英語の語順に準じれば良いですね。
なので、あんまり見ないですが、FormatterByXxxとか 後で説明するパターンもありますね。

2021-03-21 01:23 UTC, u1tnk commented on 08.ls_object/lib/parameter.rb
> +class Parameter
はい、そうです。ただそうなると入力全部処理する事になるので 名前もParameterでも悪くは無いけど微妙かも。
Inputとか InputParserとか…あたりかな 🤔

2021-03-21 01:31 UTC, u1tnk commented on 08.ls_object/test/file_list_test.rb
> +  def test_get_no_option
> minitestではbeforeではなくsetupメソッドを使う、また実行後のメソッドはteardownを使う、という認識であっていますか？
class MiniTest::Unit::TestCase

あ、そうですね。すみませんほぼ rspecしか使った事無いのでつい 😅  
ちなみにrspec or minitestは案件によって決まるのでminitestがまったく使われてないわけでは無いですので！

> テストファイルを作る際はsetup(before)内でFile.open("testfile", "w") { |f| f.print "test" }のようにファイルを作っていく、というやり方で問題ないでしょうか？
問題ない場合、実行結果は都度変わっていきますがexpectedはどのように書けばいいでしょうか？

はいその認識で大丈夫です。 また `teardown` で削除して綺麗にします。
実行結果を都度変わらないように毎回同じファイルを作って後で消すイメージですね。
ちなみに testごとに作れば他のtestに影響しないのでそのtestで確認したい最低限の状態にできますね。

2021-03-21 01:52 UTC, u1tnk commented
表にして整理すると分かりやすいですね！
コード内容を一旦忘れて機能の説明だけ見た所感です。
コード忘れるの！？って思われそうですが、クラス構成見たら大体何やってるのか分かる構成を目指して欲しいです。

- Format関連のクラスが多すぎて、役割が分かりづらいと思います。FormattedFiles/FileListFormatter が一つで良さそうに見えます。

- FileListFormatter/ (Long|Short)FileFormatter  の名前から継承関係とか同じ機能のクラスになっていそうですがFileListとその他では機能が違うのが混乱しそうですね。
    - FileListに対して FileListFormatterがある関係のようだが、 Short|LongFIleFormatterに対してのクラスが無い？ 🤔 
   
- `FileListの数だけFileFormatterを呼び出す `  FileListと複数のファイル情報が入っていそうなのに、「FIleListの数だけ」ということは複数あるということ？

2021-03-22 01:40 UTC, yana-gi commented
回答ありがとうございます！

>FileListの数だけFileFormatterを呼び出す FileListと複数のファイル情報が入っていそうなのに、「FIleListの数だけ」ということは複数あるということ？

すみません誤字です！
FormattedFilesは「FIleListの**ファイルの数だけ**FileFormatterを呼び出す」という意図のつもりでした。

>FormattedFiles/FileListFormatter が一つで良さそうに見えます。

FormattedFiles/FileListFormatterの役割を一緒にする、という認識であってますか？

>FileListFormatter/ (Long|Short)FileFormatter の名前から継承関係とか同じ機能のクラスになっていそうですがFileListとその他では機能が違うのが混乱しそうですね。

言われてみると確かにそうですね……！
FileListFormatterは「フォーマットをする」というよりは「フォーマットされたFilesを並べる」機能なのでFormattedFilesに変えてみます。

頂いた指摘をもとに一いったん以下の構成で修正してみようと思います。
修正終わり次第またご連絡します〜！

クラス | 機能
-- | --
Input | 入力処理
FileList | ファイル情報収集
ShortFileFormatter | 短いファイル情報を文字列化する
LongFileFormatter | 長いファイル情報を文字列化する
FormattedFiles | FileListのファイルの数だけFileFormatterを呼び出す、かつFormattedFilesから結果全体をフォーマットする

2021-03-22 04:20 UTC, yana-gi commented on 08.ls_object/lib/parameter.rb
> +class Parameter
ARGVごとParameter(Input)クラスに渡すように処理を変更してみたのですが、テストではエラーが発生してしまう状況です……。

コマンドライン上から実行する場合はParameter(Input)クラス上で問題なくARGVから引数や文字列を受け取れることを確認しましたのですが、テスト上でコマンドラインで渡されるARGVと同じ内容の配列を渡してみたところ、エラーが発生してしまいました。

Parameter(Input)クラスのイニシャライザ
```ruby
class Input
      attr_reader :dir_path
      
      def initialize(argv = [])
            @option = argv.getopts('alr')
            @dir_path = File.expand_path(argv[0] || '')
      end
end
```

テスト
```
class InputTest < MiniTest::Unit::TestCase
    def test_argv
      argv = ['-lar', 'aa']
      assert_equal true, Input.new(argv)
    end
end
```

テスト実行時エラー
```
Minitest::UnexpectedError: NoMethodError: undefined method `getopts' for ["-lar", "aa"]:Array
    /Users/yana/practice/ruby-practices/08.ls_object/lib/input.rb:9:in `initialize'
    /Users/yana/practice/ruby-practices/08.ls_object/test/input_test.rb:12:in `new'
    /Users/yana/practice/ruby-practices/08.ls_object/test/input_test.rb:12:in `test_argv'
/Users/yana/practice/ruby-practices/08.ls_object/lib/input.rb:9:in `initialize'
/Users/yana/practice/ruby-practices/08.ls_object/test/input_test.rb:12:in `new'
/Users/yana/practice/ruby-practices/08.ls_object/test/input_test.rb:12:in `test_argv'
```

テスト時のargvの渡し方が問題なのかなと思っているのですが、調べてもよく分からず……😭
なにかヒントがあれば教えていただけるとうれしいです！

今のところ未修正です。

2021-03-23 04:07 UTC, yana-gi commented on 08.ls_object/test/file_list_test.rb
> +  def test_get_no_option
試しにテストデータを自動で作れるように書いてみました。
`test_data_test.rb`
（試しなので変数名などは適当です）

書いてみて気になったのですが、

>実行結果を都度変わらないように毎回同じファイルを作って後で消すイメージですね。

とのことですが`-l`オプションで表示されるuid（ファイルオーナー）や作成日時も指定できるのでしょうか……？
それともexpectedに変数を埋め込むしかないのでしょうか？

2021-03-23 04:09 UTC, yana-gi commented
修正しました。
クラス名やメソッド名は見直したものの、基本的にクラスの処理はあまり変わっていないかもしれません😢

FormattedFiles（旧FormatFileList）ですが
処理の内容自体は修正前とあまり変わらないものの、「FileListのファイルの数だけFileFormatterを呼び出す」「FormattedFilesから結果全体を並び替える」処理のメソッドを意識的に分けるようにしました。
ただ、まだ機能が多いと自分でも感じるんですが、どこから見直して良いか分からずにいます……。
何かアドバイスいただけると嬉しいです🙇‍♂️

またテストデータの作成、Inputクラスに関して確認があるため合わせてご確認お願いします。

2021-03-23 14:39 UTC, u1tnk commented on 08.ls_object/lib/parameter.rb
> +class Parameter
ARGVはArrayなのですが、 https://docs.ruby-lang.org/ja/latest/class/OptionParser=3a=3aArguable.html こちらで拡張されているからですね。

テストで使うARGV も同じように拡張すれば対応可能ですし、テスト用のArrayに getoptsだけ実装するとか手はあるのすが、過剰に難しくなるので Parameterクラスの引数に `argv.getopts('alr')` したものを渡すようにするでも良いと思います。
テストしやすくする為にはシンプルなインプット/アウトプットのオブジェクトにするのがラクなので。

2021-03-23 14:57 UTC, u1tnk commented on 08.ls_object/test/file_list_test.rb
> +  def test_get_no_option
作成日時はやった事は無いので、確かに！って思いましたが https://www.atmarkit.co.jp/ait/articles/1606/14/news013.html#sample2 これでできそうです。

uidの方は chownでできると思います 💪 

こういうデータや状況の用意が自動テストの難しいところなんですよね。
ちゃんとやろうとすると大変なので必須条件から外れているわけです。
もちろんどうせ、後のプラクティスで必要になるので良い経験とは思いますよ 👍 
プラクティスとして必須では無いので、うまくいかなかった所は合格後に気がむいたときに修正するとかでも良いですからね。

ちなみにrubyはオープンクラスなのでこういのは全部mock/stubでrubyが返すメソッドを改竄してしまえばそれでもできるのですが、やり過ぎるとテストの意味が低下しちゃうんですよね。よくある悩ましいポイントです 😅

2021-03-24 15:11 UTC, u1tnk commented
> FormattedFiles/FileListFormatterの役割を一緒にする、という認識であってますか？

はい、分けなくても良いかな？と思ったので指摘しました。クラス構成整理してるところですからいったん忘れてもらって大丈夫です 🙆‍♀️ 

> FormattedFiles（旧FormatFileList）ですが
処理の内容自体は修正前とあまり変わらないものの、「FileListのファイルの数だけFileFormatterを呼び出す」「FormattedFilesから結果全体を並び替える」処理のメソッドを意識的に分けるようにしました。
ただ、まだ機能が多いと自分でも感じるんですが、どこから見直して良いか分からずにいます……。
何かアドバイスいただけると嬉しいです🙇‍♂️

最新のクラス構成も確認しました。
うーん、 今見た感じだと FormattedFiles が`FileListのファイルの数だけFileFormatterを呼び出す、かつ結果全体を並べる`なのであれば FileListみたいにファイル情報収集して複数ファイルの情報を持つのであれば一つのファイルごとのクラスにしてWc::Fileクラスにして、FormattedFilesに filesとして Wc::Fileインスタンスの配列を持つようにするとかも良いかもしれませんね。
とりあえず一案なので考えてみてください 💪

2021-04-01 08:05 UTC, yana-gi commented on 08.ls_object/lib/parameter.rb
> +class Parameter
>Parameterクラスの引数に argv.getopts('alr') したものを渡すようにするでも良いと思います。

argvごとParameterクラスに渡すのではなく、現在のInputクラスの`initialize(dir_path, option)`のままでも良い、という認識であっていますか……？

2021-04-01 08:06 UTC, yana-gi commented on 08.ls_object/test/file_list_test.rb
> +  def test_get_no_option
`touch`コマンドって変更時刻が変えられるんですね〜
イメージとしては`Kernel.#system`などで外部コマンドを実行する感じでしょうか🤔

そのヒントを貰って思い出したのですが、[module FileUtils \(Ruby 3\.0\.0 リファレンスマニュアル\)](https://docs.ruby-lang.org/ja/latest/class/FileUtils.html)を使うと外部コマンドを実行せずにRuby内で編集できそうですね……！

>プラクティスとして必須では無いので、うまくいかなかった所は合格後に気がむいたときに修正するとかでも良いですからね。

確かにそうですね、本筋のオブジェクト指向のところで苦戦しているので、ファイル作成は余力があれば修正するようにします。
色々教えていただきありがとうございます〜！

2021-04-01 08:07 UTC, yana-gi commented
>最新のクラス構成も確認しました。
うーん、 今見た感じだと FormattedFiles がFileListのファイルの数だけFileFormatterを呼び出す、かつ結果全体を並べるなのであれば FileListみたいにファイル情報収集して複数ファイルの情報を持つのであれば一つのファイルごとのクラスにしてWc::Fileクラスにして、FormattedFilesに filesとして Wc::Fileインスタンスの配列を持つようにするとかも良いかもしれませんね。
とりあえず一案なので考えてみてください 💪

`Wc::File`は`Ls::File`であってますかね……？

提案をヒントに以下のように修正を行いました。
認識が違っているところ等あればご指摘下さい！

- Ls::Fileクラスを作った
- FileListではFileではなくLs::Fileインスタンスの配列を作成させた
- FormattedFilesに引数でLs::Fileインスタンスの配列を渡すようにした

確かにLs::Fileを作ったことにより、FormattedFilesからFileFormatterインスタンスを作成しなくて済むようになりました……！

2021-04-02 01:57 UTC, u1tnk commented
> Wc::FileはLs::Fileであってますかね……？

これはその通りです 🙏

2021-04-02 06:52 UTC, u1tnk requested changes
だいぶ良くなりました！あとはクラス名整理と、FormatterFilesを改善すれば良いかと思います 👍

2021-04-02 06:52 UTC, u1tnk commented on 08.ls_object/lib/formatted_files.rb
> +class FormattedFiles
このオブジェクトはやっぱり 「フォーマットされたファイル」では無く「フォーマットするもの」である方がしっくり来そうです。
私ならこれを `Formatter`にして`Formatter::LongStyle`, `Formatter::ShortStyle`とかにするかな 🤔

2021-04-02 06:52 UTC, u1tnk commented on 08.ls_object/lib/long_file_formatter.rb
> +class LongFileFormatter
ここに入っている機能が Format機能と情報収集が混ざっているのが違和感ありますね。
ここに絶対必要なのは formatメソッドぐらいでstartとか filemodeとかuserとかはFileクラスにあるべきじゃないかと思います。
追記しておくとformatが使うprivateメソッドとして permissionを文字列化するものやmtimeを文字列化する機能があるってイメージですね。
nlinkとかは素のデータはFIleにやらせて、formatか呼び出すときに rjustすれば良いですね。

2021-04-05 06:05 UTC, yana-gi commented on 08.ls_object/lib/long_file_formatter.rb
> +class LongFileFormatter
確かにFileの情報がFormatに保管されていますね……！
Fileクラスにfileデータのハッシュを作る`build_data`メソッドを作成し、formatterに渡すように修正しました。

2021-04-05 06:05 UTC, yana-gi commented on 08.ls_object/lib/formatted_files.rb
> +class FormattedFiles
>私ならこれを FormatterにしてFormatter::LongStyle, Formatter::ShortStyleとかにするかな 🤔

すみません、ここをもう少し詳しく教えてください……！

FormatterFiles → `Formatter`
LongFileFormatter → `Formatter::LongStyle`
ShortFileFormatter → `Formatter::ShortStyle`
にするということでしょうか？

それとも`FormattedFiles`クラスの機能を`Formatter::LongStyle`と`Formatter::ShortStyle`に分けるということでしょうか？

2021-04-05 06:07 UTC, yana-gi commented
確認ありがとうございます！
確認したところ、修正したところ両方ありますので確認お願いします〜！

https://github.com/yana-gi/ruby-practices/pull/2#discussion_r605455767
またこちらのコメントの返信がいただけてないようなので確認お願いします🙏

2021-04-05 09:41 UTC, u1tnk commented on 08.ls_object/lib/parameter.rb
> +class Parameter
あ、ここの返信忘れてましたね。
はい、現在のままで良いです！

2021-04-05 09:43 UTC, u1tnk commented on 08.ls_object/lib/formatted_files.rb
> +class FormattedFiles
前者のイメージでいました！

2021-04-05 09:59 UTC, u1tnk requested changes
Formatterの機能の整理とFileからformat機能を出せれば良いと思います！

2021-04-05 09:59 UTC, u1tnk commented on 08.ls_object/lib/file.rb
> +    def build_data
一回hashに変換する必要は無いと思います。参照する方も `file.build_data[:filemode]`になっちゃうので使いづらいですし。そのままなら `file.filemode`で良いですね。(書いてて思いましたが、directoryとfileの種別で別にmodeがあるので、kindとかの方が良いかもです)

build_dataをやめて、 足りないところはメソッドを作って行く方が良いと思います！

2021-04-05 09:59 UTC, u1tnk commented on 08.ls_object/lib/formatted_files.rb
> +    formatted_files = @files.create_files.map(&:format)
fileごとにformat呼んでると思うのですが、以下のようにすればformat機能をFileから出せると思います。
Fileにはpathだけあれば良くて Inputは不要だと思うので。

```
 formatted_files = @files.create_files.map do
      if @input.long_format?
        LongFileFormatter.new(@input.dir_path, build_data).format
      else
        ShortFileFormatter.new(@file_name).format
      end
end
```

2021-04-07 04:27 UTC, yana-gi commented on 08.ls_object/lib/formatted_files.rb
> +    formatted_files = @files.create_files.map(&:format)
fileクラスからformat機能を削除しました。
FileからLongStyleを呼び出すとFileのインスタンスが渡せないなと思っていたのですが、
Formatterから呼び出せばよかったんですね！

2021-04-07 04:27 UTC, yana-gi commented on 08.ls_object/lib/file.rb
> +    def build_data
build_dataをやめ、メソッドを作る形に修正しました。

2021-04-07 04:27 UTC, yana-gi commented on 08.ls_object/lib/formatted_files.rb
> +class FormattedFiles
なるほど！
以下のように変更しました。
FormatterFiles → `Formatter`
LongFileFormatter → `LongStyle`
ShortFileFormatter → `ShortStyle`

>Formatterを継承した LogStyle/ShortStyleにした方が良いかもしれません！

とのことですが、継承をあまり理解していないので確認させてください！
子クラスが親クラスを継承すると、親クラスのメソッドを使えるようになると思いますが、
今回のケースだとLogStyle/ShortStyleはFormatterのメソッドを使わないですし、同名のメソッドをオーバーライドして使えるところも無いように見えます。
今回継承すると何がいい（嬉しい）のでしょうか……？

（ちなみに試しにFormatterを継承してみたのですが、エラーがでてしまいうまく継承できずにいます😭）

それか継承を使わず`Formatter`という名前空間を作り`Formatter`（FormatterFiles）を`ListStyle`にするという手もありますかね？🤔
`Formatter::ListStyle`
`Formatter::LongRowStyle`
`Formatter::ShortRowStyle`

2021-04-14 02:57 UTC, yana-gi commented
ペアプロで教えて頂いたことやpushして頂いたコードを参考に修正しました。
ご確認お願いしますー🙏

2021-04-22 06:11 UTC, merged